# Generated by Django 2.1.5 on 2021-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210805_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('drinks', 'drinks'), ('desserts', 'desserts'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
