# Generated by Django 2.1.5 on 2021-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('The Honourable', 'The Honourable'), ('Her Honour', 'Her Honour'), ('Excellency', 'Excellency'), ('Lord', 'Lord'), ('Dame', 'Dame'), ('Esquire', 'Esquire'), ('Doctor', 'Doctor'), ('Sir', 'Sir.'), ('----------', '----------'), ('Lady', 'Lady.'), ('His Honour', 'His Honour'), ('The Right Honourable', 'The Right Honourable'), ('Sire', 'Sire')], default='----------', max_length=20),
        ),
    ]
