# Generated by Django 2.1.5 on 2021-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Lord', 'Lord'), ('Her Honour', 'Her Honour'), ('Sire', 'Sire'), ('Excellency', 'Excellency'), ('His Honour', 'His Honour'), ('Sir', 'Sir.'), ('The Right Honourable', 'The Right Honourable'), ('Dame', 'Dame'), ('Lady', 'Lady'), ('Esquire', 'Esquire'), ('Doctor', 'Doctor'), ('The Honourable', 'The Honourable')], default='----------', max_length=20),
        ),
    ]
