# Generated by Django 2.1.5 on 2021-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210805_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Her Honour', 'Her Honour'), ('Excellency', 'Excellency'), ('----------', '----------'), ('Sir', 'Sir'), ('The Right Honourable', 'The Right Honourable'), ('His Honour', 'His Honour'), ('Lord', 'Lord'), ('The Honourable', 'The Honourable'), ('Doctor', 'Doctor'), ('Esquire', 'Esquire'), ('Dame', 'Dame'), ('Lady', 'Lady'), ('Sire', 'Sire')], default='----------', max_length=20),
        ),
    ]
