# Generated by Django 2.1.5 on 2021-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210805_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Sir', 'Sir'), ('His Honour', 'His Honour'), ('The Right Honourable', 'The Right Honourable'), ('Her Honour', 'Her Honour'), ('Dame', 'Dame'), ('Doctor', 'Doctor'), ('----------', '----------'), ('Lady', 'Lady'), ('Sire', 'Sire'), ('Esquire', 'Esquire'), ('Lord', 'Lord'), ('Excellency', 'Excellency'), ('The Honourable', 'The Honourable')], default='----------', max_length=20),
        ),
    ]
