# Generated by Django 2.1.5 on 2021-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210805_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Lady', 'Lady'), ('Sir', 'Sir'), ('The Right Honourable', 'The Right Honourable'), ('Dame', 'Dame'), ('The Honourable', 'The Honourable'), ('Lord', 'Lord'), ('Her Honour', 'Her Honour'), ('Sire', 'Sire'), ('His Honour', 'His Honour'), ('Doctor', 'Doctor'), ('Esquire', 'Esquire'), ('----------', '----------'), ('Excellency', 'Excellency')], default='----------', max_length=20),
        ),
    ]
