# Generated by Django 2.1.5 on 2021-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210805_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('His Honour', 'His Honour'), ('Dame', 'Dame'), ('Her Honour', 'Her Honour'), ('Lord', 'Lord'), ('The Right Honourable', 'The Right Honourable'), ('Doctor', 'Doctor'), ('Lady', 'Lady'), ('The Honourable', 'The Honourable'), ('----------', '----------'), ('Sire', 'Sire'), ('Excellency', 'Excellency'), ('Esquire', 'Esquire'), ('Sir', 'Sir')], default='----------', max_length=20),
        ),
    ]
