# Generated by Django 2.1.5 on 2021-08-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210805_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('The Right Honourable', 'The Right Honourable'), ('Doctor', 'Doctor'), ('The Honourable', 'The Honourable'), ('Esquire', 'Esquire'), ('----------', '----------'), ('Lord', 'Lord'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Her Honour', 'Her Honour'), ('Excellency', 'Excellency'), ('Dame', 'Dame'), ('Sire', 'Sire'), ('His Honour', 'His Honour')], default='----------', max_length=20),
        ),
    ]
