# Generated by Django 2.1.5 on 2021-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210805_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Excellency', 'Excellency'), ('Lady', 'Lady'), ('Dame', 'Dame'), ('Lord', 'Lord'), ('His Honour', 'His Honour'), ('Sir', 'Sir'), ('The Honourable', 'The Honourable'), ('Sire', 'Sire'), ('Doctor', 'Doctor'), ('Her Honour', 'Her Honour'), ('The Right Honourable', 'The Right Honourable'), ('----------', '----------'), ('Esquire', 'Esquire')], default='----------', max_length=20),
        ),
    ]
