# Generated by Django 2.1.5 on 2021-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210806_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('The Right Honourable', 'The Right Honourable'), ('Esquire', 'Esquire'), ('His Honour', 'His Honour'), ('Doctor', 'Doctor'), ('----------', '----------'), ('Sire', 'Sire'), ('Lady', 'Lady'), ('Her Honour', 'Her Honour'), ('Excellency', 'Excellency'), ('Sir', 'Sir'), ('Dame', 'Dame'), ('The Honourable', 'The Honourable'), ('Lord', 'Lord')], default='----------', max_length=20),
        ),
    ]
