# Generated by Django 2.1.5 on 2021-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210806_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Lady', 'Lady'), ('Sir', 'Sir'), ('Her Honour', 'Her Honour'), ('The Right Honourable', 'The Right Honourable'), ('The Honourable', 'The Honourable'), ('Lord', 'Lord'), ('His Honour', 'His Honour'), ('Excellency', 'Excellency'), ('Doctor', 'Doctor'), ('Sire', 'Sire'), ('Dame', 'Dame'), ('Esquire', 'Esquire'), ('----------', '----------')], default='----------', max_length=20),
        ),
    ]
