# Generated by Django 2.1.5 on 2021-08-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210806_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('----------', '----------'), ('The Honourable', 'The Honourable'), ('Sir', 'Sir'), ('Lord', 'Lord'), ('Her Honour', 'Her Honour'), ('The Right Honourable', 'The Right Honourable'), ('Dame', 'Dame'), ('His Honour', 'His Honour'), ('Lady', 'Lady'), ('Esquire', 'Esquire'), ('Sire', 'Sire'), ('Excellency', 'Excellency'), ('Doctor', 'Doctor')], default='----------', max_length=20),
        ),
    ]
