# Generated by Django 2.1.5 on 2021-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20210806_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Her Honour', 'Her Honour'), ('Sire', 'Sire'), ('Lady', 'Lady'), ('Sir', 'Sir'), ('Excellency', 'Excellency'), ('Lord', 'Lord'), ('Esquire', 'Esquire'), ('Doctor', 'Doctor'), ('----------', '----------'), ('Dame', 'Dame'), ('The Honourable', 'The Honourable'), ('The Right Honourable', 'The Right Honourable'), ('His Honour', 'His Honour')], default='----------', max_length=20),
        ),
    ]
