# Generated by Django 2.1.5 on 2021-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210806_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('----------', '----------'), ('Excellency', 'Excellency'), ('Dame', 'Dame'), ('Sire', 'Sire'), ('Lord', 'Lord'), ('The Honourable', 'The Honourable'), ('His Honour', 'His Honour'), ('Doctor', 'Doctor'), ('Her Honour', 'Her Honour'), ('Sir', 'Sir'), ('The Right Honourable', 'The Right Honourable'), ('Lady', 'Lady'), ('Esquire', 'Esquire')], default='----------', max_length=20),
        ),
    ]
