# Generated by Django 2.2.5 on 2021-08-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_auto_20210819_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('Name', 'id')},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Favorite',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Publisher',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Thumbnail',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Year',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
